### PR TITLE
misra.py: Add relative suppressions

### PR DESCRIPTION
**Pull request by jubnzv**
See: https://github.com/danmar/cppcheck/pull/2771

### CODE REVIEW

**Comment by petr-nechaev** [comment]
@jubnzv   I changed the target of this PR to my branch.  If you are ok I will remove my commit 62c9c087abb3952f937558a53af4d708614f5f71

**Comment by jubnzv** [comment]
@petr-nechaev yes, of course. Will this require any changes from me?

**Comment by petr-nechaev** [comment]
@jubnzv   Is this PR still valid considering changes in https://github.com/danmar/cppcheck/commit/a810678b8313203c9be814554bbb3a5eebf162f5#diff-d867773a35a994c76a3a6a7a39f8af7b5bf5c45a031d6a27bc01fddab1b11546    ?

**Comment by jubnzv** [comment]
@petr-nechaev No, this PR is no longer needed. The `misra.py` from the upstream supports suppressions with relative paths.

**Pull request closed without merging**
